### ISSUE TITLE
[lab4] Compilation/build error

### ISSUE THREAD

**Issue by FireEmerald** [zirpins/bdelab#5]
Using a plain copy of the provided files from git produces the following output after `mvn package`:

```
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 6 source files to /home/stud/lkt/fbi/mech1027/git/bdelab/lab4/stormwordcount/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /home/stud/lkt/fbi/mech1027/git/bdelab/lab4/stormwordcount/src/main/java/de/hska/iwi/vsys/bdelab/streaming/TopicTupleBuilder.java:[4,36] cannot find symbol
  symbol:   class KafkaSpoutTupleBuilder
  location: package org.apache.storm.kafka.spout
[ERROR] /home/stud/lkt/fbi/mech1027/git/bdelab/lab4/stormwordcount/src/main/java/de/hska/iwi/vsys/bdelab/streaming/TopicTupleBuilder.java:[15,46] cannot find symbol
  symbol: class KafkaSpoutTupleBuilder
[ERROR] /home/stud/lkt/fbi/mech1027/git/bdelab/lab4/stormwordcount/src/main/java/de/hska/iwi/vsys/bdelab/streaming/SentenceSpout.java:[35,26] cannot find symbol
  symbol:   class KafkaSpoutStreams
  location: class de.hska.iwi.vsys.bdelab.streaming.SentenceSpout
[ERROR] /home/stud/lkt/fbi/mech1027/git/bdelab/lab4/stormwordcount/src/main/java/de/hska/iwi/vsys/bdelab/streaming/SentenceSpout.java:[38,26] cannot find symbol
  symbol:   class KafkaSpoutTuplesBuilder
  location: class de.hska.iwi.vsys.bdelab.streaming.SentenceSpout
[INFO] 4 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.994 s
[INFO] Finished at: 2019-01-02T18:19:16+01:00
[INFO] Final Memory: 22M/326M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project storm-page-views-ref: Compilation failure: Compilation failure:
[ERROR] /home/stud/lkt/fbi/mech1027/git/bdelab/lab4/stormwordcount/src/main/java/de/hska/iwi/vsys/bdelab/streaming/TopicTupleBuilder.java:[4,36] cannot find symbol
[ERROR] symbol:   class KafkaSpoutTupleBuilder
[ERROR] location: package org.apache.storm.kafka.spout
[ERROR] /home/stud/lkt/fbi/mech1027/git/bdelab/lab4/stormwordcount/src/main/java/de/hska/iwi/vsys/bdelab/streaming/TopicTupleBuilder.java:[15,46] cannot find symbol
[ERROR] symbol: class KafkaSpoutTupleBuilder
[ERROR] /home/stud/lkt/fbi/mech1027/git/bdelab/lab4/stormwordcount/src/main/java/de/hska/iwi/vsys/bdelab/streaming/SentenceSpout.java:[35,26] cannot find symbol
[ERROR] symbol:   class KafkaSpoutStreams
[ERROR] location: class de.hska.iwi.vsys.bdelab.streaming.SentenceSpout
[ERROR] /home/stud/lkt/fbi/mech1027/git/bdelab/lab4/stormwordcount/src/main/java/de/hska/iwi/vsys/bdelab/streaming/SentenceSpout.java:[38,26] cannot find symbol
[ERROR] symbol:   class KafkaSpoutTuplesBuilder
[ERROR] location: class de.hska.iwi.vsys.bdelab.streaming.SentenceSpout
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

Downgrading storm.version to `1.0.3` fixes the problem:
https://github.com/zirpins/bdelab/blob/ed790abcc0f7c19ae2289af14171bc28e4e014fd/lab4/stormwordcount/pom.xml#L14

But the execution of the `WordcountTopology` example script produces:
<details>

```
295  [main] INFO  o.a.s.k.s.KafkaSpoutStream - Declared [streamId = sentence_stream], [outputFields = [topic, partition, offset, key, value]] for [topic = sentence_mech1027]
328  [main] INFO  o.a.s.StormSubmitter - Generated ZooKeeper secret payload for MD5-digest: -8150840768476150489:-7471028819088582636
372  [main] INFO  o.a.s.s.a.AuthUtils - Got AutoCreds []
10425 [main] WARN  o.a.s.u.NimbusClient - Ignoring exception while trying to get leader nimbus info from localhost. will retry with a different seed host.
java.lang.RuntimeException: java.lang.RuntimeException: org.apache.storm.thrift.transport.TTransportException: java.net.ConnectException: Connection refused
        at org.apache.storm.security.auth.ThriftClient.reconnect(ThriftClient.java:108) ~[storm-page-views-ref-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.storm.security.auth.ThriftClient.<init>(ThriftClient.java:69) ~[storm-page-views-ref-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.storm.utils.NimbusClient.<init>(NimbusClient.java:124) ~[storm-page-views-ref-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.storm.utils.NimbusClient.getConfiguredClientAs(NimbusClient.java:82) [storm-page-views-ref-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.storm.StormSubmitter.topologyNameExists(StormSubmitter.java:370) [storm-page-views-ref-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.storm.StormSubmitter.submitTopologyAs(StormSubmitter.java:233) [storm-page-views-ref-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.storm.StormSubmitter.submitTopology(StormSubmitter.java:310) [storm-page-views-ref-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.storm.StormSubmitter.submitTopologyWithProgressBar(StormSubmitter.java:346) [storm-page-views-ref-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.storm.StormSubmitter.submitTopologyWithProgressBar(StormSubmitter.java:327) [storm-page-views-ref-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at de.hska.iwi.vsys.bdelab.streaming.WordcountTopology.main(WordcountTopology.java:38) [storm-page-views-ref-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
Caused by: java.lang.RuntimeException: org.apache.storm.thrift.transport.TTransportException: java.net.ConnectException: Connection refused
        at org.apache.storm.security.auth.TBackoffConnect.retryNext(TBackoffConnect.java:64) ~[storm-page-views-ref-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.storm.security.auth.TBackoffConnect.doConnectWithRetry(TBackoffConnect.java:56) ~[storm-page-views-ref-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.storm.security.auth.ThriftClient.reconnect(ThriftClient.java:100) ~[storm-page-views-ref-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        ... 9 more
Caused by: org.apache.storm.thrift.transport.TTransportException: java.net.ConnectException: Connection refused
        at org.apache.storm.thrift.transport.TSocket.open(TSocket.java:226) ~[storm-page-views-ref-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.storm.thrift.transport.TFramedTransport.open(TFramedTransport.java:81) ~[storm-page-views-ref-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.storm.security.auth.SimpleTransportPlugin.connect(SimpleTransportPlugin.java:105) ~[storm-page-views-ref-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.storm.security.auth.TBackoffConnect.doConnectWithRetry(TBackoffConnect.java:53) ~[storm-page-views-ref-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.storm.security.auth.ThriftClient.reconnect(ThriftClient.java:100) ~[storm-page-views-ref-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        ... 9 more
Caused by: java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_72-internal]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_72-internal]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_72-internal]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_72-internal]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_72-internal]
        at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_72-internal]
        at org.apache.storm.thrift.transport.TSocket.open(TSocket.java:221) ~[storm-page-views-ref-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.storm.thrift.transport.TFramedTransport.open(TFramedTransport.java:81) ~[storm-page-views-ref-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.storm.security.auth.SimpleTransportPlugin.connect(SimpleTransportPlugin.java:105) ~[storm-page-views-ref-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.storm.security.auth.TBackoffConnect.doConnectWithRetry(TBackoffConnect.java:53) ~[storm-page-views-ref-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.storm.security.auth.ThriftClient.reconnect(ThriftClient.java:100) ~[storm-page-views-ref-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        ... 9 more
Exception in thread "main" java.lang.RuntimeException: org.apache.storm.utils.NimbusLeaderNotFoundException: Could not find leader nimbus from seed hosts [localhost]. Did you specify a valid list of nimbus hosts for config nimbus.seeds?
        at org.apache.storm.StormSubmitter.topologyNameExists(StormSubmitter.java:380)
        at org.apache.storm.StormSubmitter.submitTopologyAs(StormSubmitter.java:233)
        at org.apache.storm.StormSubmitter.submitTopology(StormSubmitter.java:310)
        at org.apache.storm.StormSubmitter.submitTopologyWithProgressBar(StormSubmitter.java:346)
        at org.apache.storm.StormSubmitter.submitTopologyWithProgressBar(StormSubmitter.java:327)
        at de.hska.iwi.vsys.bdelab.streaming.WordcountTopology.main(WordcountTopology.java:38)
Caused by: org.apache.storm.utils.NimbusLeaderNotFoundException: Could not find leader nimbus from seed hosts [localhost]. Did you specify a valid list of nimbus hosts for config nimbus.seeds?
        at org.apache.storm.utils.NimbusClient.getConfiguredClientAs(NimbusClient.java:108)
        at org.apache.storm.StormSubmitter.topologyNameExists(StormSubmitter.java:370)
        ... 5 more
```

</details>

**Comment by zirpins** [comment]
Thanks for noticing!

Quick-fixed compilation by downgrading storm (but should really be upgraded sometime soon).

Please note that you need to run the topology in LKIT. As of now, zookeeper and kafka servers are operational (again). 

Let me know, if problem persists.
